Models/Teacher.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace MvcStudent.Models
{
    public class Teacher
    {
        public int Id { get; set; }
        public string Name { get; set; }

        [DataType(DataType.Date)]
        public DateTime HireDate { get; set; }
        public string Group { get; set; }
        public string Classroom { get; set; }
        public decimal Ratings { get; set; }
    }
}

Controllers/TeachersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MvcStudent.Data;
using MvcStudent.Models;

namespace MvcStudent.Controllers
{
    public class TeachersController : Controller
    {
        private readonly MvcTeacherContext _context;

        public TeachersController(MvcTeacherContext context)
        {
            _context = context;
        }

        // GET: Teachers

       public async Task<IActionResult> Index(string searchString)
        {
            var teachers = from m in _context.Teacher
                         select m;

            if (!String.IsNullOrEmpty(searchString))
            {
                teachers = teachers.Where(s => s.Name.Contains(searchString));
            }


            return View(await teachers.ToListAsync());
        }
       



        // GET: Teachers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var teacher = await _context.Teacher
                .FirstOrDefaultAsync(m => m.Id == id);
            if (teacher == null)
            {
                return NotFound();
            }

            return View(teacher);
        }

        // GET: Teachers/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Teachers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,HireDate,Group,Classroom,Ratings")] Teacher teacher)
        {
            if (ModelState.IsValid)
            {
                _context.Add(teacher);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(teacher);
        }

        // GET: Teachers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var teacher = await _context.Teacher.FindAsync(id);
            if (teacher == null)
            {
                return NotFound();
            }
            return View(teacher);
        }

        // POST: Teachers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,HireDate,Group,,Classroom,Ratings")] Teacher teacher)
        {
            if (id != teacher.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(teacher);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TeacherExists(teacher.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(teacher);
        }

        // GET: Teachers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var teacher = await _context.Teacher
                .FirstOrDefaultAsync(m => m.Id == id);
            if (teacher == null)
            {
                return NotFound();
            }

            return View(teacher);
        }

        // POST: Teachers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var teacher = await _context.Teacher.FindAsync(id);
            _context.Teacher.Remove(teacher);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TeacherExists(int id)
        {
            return _context.Teacher.Any(e => e.Id == id);
        }
    }
}

Views/Teachers/Create.cshtml
@model MvcStudent.Models.Teacher

@{
    ViewData["Title"] = "Create";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>

    <h3 style="margin-top:30px;">Teachers List</h3>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Name" class="control-label"></label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="HireDate" class="control-label"></label>
                    <input asp-for="HireDate" class="form-control" />
                    <span asp-validation-for="HireDate" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Group" class="control-label"></label>
                    <input asp-for="Group" class="form-control" />
                    <span asp-validation-for="Group" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Classroom" class="control-label"></label>
                    <input asp-for="Classroom" class="form-control" />
                    <span asp-validation-for="Classroom" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Ratings" class="control-label"></label>
                    <input asp-for="Ratings" class="form-control" />
                    <span asp-validation-for="Ratings" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>

    <div>
        <a asp-action="Index">Back to List</a>
    </div>

</body>
</html>

Views/Teachers/Delete.cshtml
@model MvcStudent.Models.Teacher

@{
    ViewData["Title"] = "Delete";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>

<h3 style="margin-top:30px;">Are you sure you want to delete this?</h3>
<div>
    <h4 style="margin-top:30px;">Teacher</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.HireDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.HireDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Group)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Group)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Classroom)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Classroom)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Ratings)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Ratings)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>
</body>
</html>

Views/Teachers/Details.cshtml
@model MvcStudent.Models.Teacher

@{
    ViewData["Title"] = "Details";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>

    <div>
        <h3 style="margin-top:30px;">Teacher</h3>
        <hr />
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Name)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Name)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.HireDate)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.HireDate)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Group)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Group)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Classroom)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Classroom)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Ratings)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Ratings)
            </dd>
        </dl>
    </div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>
</body>
</html>

Views/Teachers/Edit.cshtml
@model MvcStudent.Models.Teacher

@{
    ViewData["Title"] = "Edit";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
</head>
<body>

    <h3 style="margin-top:30px;">Teacher</h3>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Edit">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="Id" />
                <div class="form-group">
                    <label asp-for="Name" class="control-label"></label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="HireDate" class="control-label"></label>
                    <input asp-for="HireDate" class="form-control" />
                    <span asp-validation-for="HireDate" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Group" class="control-label"></label>
                    <input asp-for="Group" class="form-control" />
                    <span asp-validation-for="Group" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Classroom" class="control-label"></label>
                    <input asp-for="Classroom" class="form-control" />
                    <span asp-validation-for="Classroom" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Ratings" class="control-label"></label>
                    <input asp-for="Ratings" class="form-control" />
                    <span asp-validation-for="Ratings" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Save" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>

    <div>
        <a asp-action="Index">Back to List</a>
    </div>

</body>
</html>

Views/Teachers/Index.cshtml
@model IEnumerable<MvcStudent.Models.Teacher>

@{
    ViewData["Title"] = "Index";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>

    <h3 style="margin-top:30px;">Teachers List</h3>
    <form asp-controller="Teachers" asp-action="Index" method="get">
        <p>
            Name: <input type="text" name="SearchString">
            <input type="submit" value="Filter" />
        </p>
    </form>
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.HireDate)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Group)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Classroom)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Ratings)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.HireDate)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Group)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Classroom)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Ratings)
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                        <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                        <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>

    <form>
        <button class="btn btn-primary mb-2" asp-action="Create">Create new teacher</button>
    </form>
</body>
</html>